### ISSUE TITLE
Cache results of validated justifications to short-circuit future message verification

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#131]
Each unique vote value in the protocol only needs to be justified once. After receiving a message with justified value V from one participant, a node need not check the justification received with other messages carrying the same V. This is a huge optimisation, probably necessary for feasible protocol execution at scale.

**Comment by Kubuxu** [comment]
We might have to do this sooner than later.

**Comment by Stebalien** [comment]
From F3 standup discussions: this isn't quite so simple.

1. We can't re-broadcast messages with invalid justifications, even if we've seen a valid justification.
2. We can't easily replace the message's justification given that pubsub messages are signed (and identified by the original sender/nonce).
3. We _can_ disable pubsub signatures and identify messages by their GPBFT payload, but, unfortunately, we use message IDs to deduplicate messages _before_ validating them. That means, if we receive a message with payload X and mark it as invalid (e.g., has an invalid justification) then receive the same payload X with a correct justification, pubsub will drop it before validation because we're identifying inbound messages by payload value.

The solution to all this is to give pubsub two different ways of identifying messages:

1. For pre-validation deduplication, identify messages by hash, always.
2. Only use the user-configurable message ID _after_ validation (to determine if we should rebroadcast the message, to identify messages in gossip, etc.).

However, we'd _additionally_ need the ability to _mutate_ pubsub messages: replace the possibly invalid justification (the one we didn't bother checking) with the known valid justification (from our cache).

**Comment by masih** [comment]
Closing now that both #557 and #560  are merged. Please feel free to reopen if there is more here to do.
