### ISSUE TITLE
Implement finality decision exchange protocol

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#15]
Design and implement an exchange protocol for finality certificates. See [design doc](https://docs.google.com/document/d/10i9tFremOSrZou9oO5A5wvu1uOy1lvFKbv8IsvoglR0/edit).

**Comment by Stebalien** [comment]
Thinking about this, I'm not convinced this should live in go-f3.

- Finality certificates will be stored in the client.
- The client will be handling the inbound libp2p requests.
- The client will need to pick the peers to query for finality certificates (and possibly manage reputation).

I'm wondering if, instead, we want to flip control: provide a way to create, validate, and parse finality certificates but put the actual finality certificate protocol implementation in the client.

**Comment by Kubuxu** [comment]
I disagree, as then there exists an external piece of code that is required to run F3. My goal is such that F3 forms a complete system, I don't see a compelling reason for externalising it or creating another layer of abstraction (gpbft and libp2p are these layers of abstraction).

**Comment by Stebalien** [comment]
We have a few options:

1. Let F3 understand the concept of different "peers". The client provides a set of peers to F3, a stream abstraction, and a finality certificate store.
2. Handle "peers" in the client. I.e., F3 asks the client "send this encoded message to some peer, and return me the result".
3. Handle encoding in the client as well. F3 tells the client "I'm requesting this range of finality certificates", the client returns the response.
4. Handle validation in the client as well (via callbacks into F3). F3 asks the client for a range of finality certificates, the client keeps asking different peers for finality certificates it gets a valid set.

I'm proposing option 4.

Option 1 works, but it leaks a bunch of information into F3 and forces the client to use a specific stream-oriented protocol (e.g., can't use JSON-RPC, etc.).

Option 2/3 are problematic because there's no way for the client to validate the response:

- The client will need feedback from F3 about validity for reputation tracking.
- F3 needs to be able to go back to the client and ask it "try again from instance X, but don't trust any peers you asked last time". Basically, the client implementation can't be simple.

Option 2 has an additional problem: like option 1, it's handles message encoding and therefore won't be as compatible with alternative transports like JSON-RPC.

Option 4 is _like_ option 3, except that the client can call back into F3 (as a library) to validate finality certificates. Basically:

1. F3 asks the client "give me all finality certificates starting at instance X".
2. The client asks peers for finality certificates in any manner they wish (RPC, libp2p, etc.).
3. The client asks F3 (as a library) to validate finality certificates.
4. The client streams back _validated_ finality certificates (to F3).

**Comment by Kubuxu** [comment]
We are over-abstracting. Why not have a finality exchange protocol straight in F3 using libp2p interfaces?
If we want to develop another transport for this protocol, we can do it here as well.

**Comment by anorth** [comment]
I concur with @Kubuxu  at least as far as that we should be able to have a complete stand-alone implementation of F3 in this repo. That doesn't preclude other implementations of certificate exchange, and API flexibility to make it easy to inject certificates obtained elsewhere (e.g. HTTP) would be good.

Possibly some repo rework like #155 would help separate a finality exchange protocol from the core F3 protocol, while keeping this repo a home for a complete implementation.

**Comment by Wondertan** [comment]
I'm passing by to give you another option. In Celestia, we had an almost identical problem with headers and finality proofs, so we ended up designing the [go-header](https://github.com/celestiaorg/go-header) library. It is production-ready, battle-tested, and covered with metrics. It follows the PL library design philosophy a lot and nicely separates concerns, so you might find it useful. 

In its core, there is the [Header iface](https://github.com/celestiaorg/go-header/blob/88c5b8ce22fab78d0c589b8762bdd7faf89c9349/header.go#L11), and our implementation couples Header + finality signatures. By simply implementing the iface, you get Store, Exchange, and Syncing out of the box. As long as your finality certificate data structure forms a chain and can be verified against each other, the go-header will work without any modifications.  

It should be noted that Celestia would happily contribute back somehow to PL and Filecoin, considering how helpful it was for us to piggyback on libp2p and ipfs primitives.

**Comment by Stebalien** [comment]
It looks interesting, but our protocol doesn't quite fit, primarily because we don't create a hash chain of headers (F3 is _not_ a block chain). In our case, we have finality certificates for each "instance" but we can have multiple finality certificates per instance signed by different subsets of the power. In theory, F3 could try to come to consensus on the "canonical" finality certificate for any given F3 instance, but not with the way the protocol is currently built.

Our headers also aren't quite atomic at the moment: we rely on power table diffs and commitment to avoid having to include the entire power table. Eventually we plan on replacing these with snarked proofs and snark-friendly power table commitments which should let us have "atomic" headers, but these headers still aren't unique.

**Comment by Stebalien** [comment]
Basic protocol:

```go
type Request struct {
	// Network name
	Network NetworkName
	// First instance to fetch.
	Start uint64
	// Max number of instances to fetch.
	Limit uint64
	// Include the full power table needed to validate the instance.
	// Checked by the user against their finality certificate.
	IncludePowerTable bool
}
type Response struct {
	// Finality certificates...
	Certificates []FinalityCertificate
	// Power table, if requested, or empty
	PowerTable []PowerEntry
}
```

**Comment by Stebalien** [comment]
Feedback: find a way to return an error.

**Comment by anorth** [comment]
Is FinalityCertificate as defined in https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0086.md?

Is the optionally included power table the one used to validate the _first_ certificate returned? Note that with lookback this won't be sufficient to validate the _second_ certificate. You also need the deltas from the lookback period.

**Comment by Stebalien** [comment]
> Is FinalityCertificate as defined in https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0086.md?

Yes.

Overall, finality lookback complicates this. My initial plan was to include the power deltas necessary to validate the next instance (i.e., taking lookback into account). I'll have to think about it (want to avoid juggling multiple power tables).
