### ISSUE TITLE
Import CID library and use real CIDs

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#18]
The core Granite code treats CIDs as opaque, but higher level components will need to compute CIDs, e.g. of the power table. The most pragmatic option is probably to use the CID type (even though Granite could use `[]byte`).

**Comment by anorth** [comment]
After beginning this, I was dissatisfied with the array of dependencies brought in by the go-cid package. Considering CIDs are entirely opaque for this protocol, I will instead replace the simple string typedef with an opaque struct. This will bring a little type safely, while being an easy type to convert actual CIDs (or Lotus TipSetKey or similar) into.

**Comment by Stebalien** [comment]
I'm going to re-open this issue because it has come up a few times with respect to power table CIDs. Especially in the context of finality certificates as it would be _nice_ if they were "proper" IPLD.

- I have a few error messages that would be nicer with go-cid (base32 encoded CIDs). Not critical, but a semi-decent reason.
- We have some objects (finality certificates & tipsets) that include these CIDs and cross boundaries to and from the client. It would be nice to not have to convert types here.
- The DagCBOR encoding of finality certificates is going to be incorrect unless we use go-cid (CIDs won't be marked as CIDs).
- We're already importing go-cid via cbor-gen. We've already discussed this little fact, but at the time, we didn't have any _additional_ reasons to switch to it. Now, IMO, we do.

I'm happy to take this if there are no objections.

**Comment by anorth** [comment]
Ok. I would still like to avoid importing CID in the core protocol module if possible, but fine to use it in the integration parts. If we used a Go workspace, we could more easily enforce this.

**Comment by Stebalien** [comment]
That's going to be tricky unless we have a separate `TipSet` type for finality certificates versus messages (which would be more of a pain than its worth, IMO).

**Comment by anorth** [comment]
Sure, just because I would like it doesn't mean we can do it.
