### ISSUE TITLE
Implement the DECIDE phase with strong quorum

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#2]
The protocol is to be updated by making the DECIDE phase mandatory, completing only after receiving a strong quorum of DECIDE messages.

- Add the DECID phase, moving the decision point of the instance until after a strong quorum of such messages are gathered
- Re-use the existing quorum state helpers

**Comment by matejpavlovic** [comment]
Currently, the round in which an instance decided is part of that instance's interface ([the Finalised() function returns it](https://github.com/filecoin-project/go-f3/blob/3a6c2283ef9a7b86e2ad36c95e24ecfda5b00cb9/f3/participant.go#L37C18-L37C18)). This becomes not-so-well-defined when we introduce the DECIDE messages, since a participant can decide based on a quorum containing DECIDE messages carrying decisions from different rounds.

What I can imagine to do about it:
1. Define (and implement) how a quorum of DECIDE messages carrying their respective decision rounds maps to a single round in which we consider the recipient of those messages to have decided. E.g. this could be the f+1st quantile of the rounds contained in the DECIDE messages.
2. Drop that concept altogether and simply not indicate which round the decision was taken in.

Any preferences or other suggestions @anorth ?

**Comment by anorth** [comment]
As discussed, the internal evidence signature for a DECIDE message should always use round zero, so these can be aggregated. But otherwise keep propagating it since its useful for tracing and debugging protocol executions.
