### ISSUE TITLE
`instance.roundState(round)` is a (minor) DoS vector

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/go-f3#208]
IIRC, the plan to avoid storing arbitrary messages was to:

1. Store at most one "quality" value from every miner.
2. ignore all messages from future rounds that lack justification from a prior round (again, at most once per miner).

However, `roundState` implicitly allocates a round object before we even look at the message. It's possible for a miner to repeatedly send the _same_ quality message but with different rounds, forcing us to allocate a bunch of round states.

This will _probably_ get fixed when we implement the above but... it's a subtle implicit allocation that's easily overlooked, so I wanted to write this down so we don't forget.

**Comment by Stebalien** [comment]
Part of #12.

**Comment by anorth** [comment]
Now that validation is performed, before messages are received and because quality messages are only valid for round zero, the specific motivating case here can't happen. And now that we've implemented dropping of far future spammable messages, I think this is mostly resolved. I have one change coming to avoid loading round state for post-receive checks (e.g. skipping rounds) in case a message could not have had any effect.
