### ISSUE TITLE
Consider protection against concurrent invocation of ReceiveMessage and ReceiveAlarm

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#304]
There are two stateful methods in the participant API exposed to the host: ReceiveMessage and ReceiveAlarm. If invoked concurrently, unpredictable things might happen.

What, if anything, should we do about this? The simplest answer is probably to declare that these messages are not safe for concurrent use and expect the host, Lotus, to use them safely.

**Comment by Stebalien** [comment]
My understanding is that `ValidateMessage` is the only one safe to be invoked concurrently.

Honestly, adding an atomic flag to these methods may not be a bad idea (so we can return an error if they get invoked concurrently). It should have no noticeable performance impact.

**Comment by masih** [comment]
Considering the sensitivity of that code path I would use a simple mutex for safety alone. That seems like the path of least resistance. 

At a higher level it would be nice to refactor the protocol as a simple set of actors (as in actor model). But that's a bigger body of work with an unclear ROI.

**Comment by Stebalien** [comment]
> Considering the sensitivity of that code path I would use a simple mutex for safety alone. That seems like the path of least resistance.

I suggested an atomic plus an error (or a TryLock plus an error) because the user _is not_ supposed to call these methods concurrently and I'd rather catch that early. However, I don't feel strongly about this.

> At a higher level it would be nice to refactor the protocol as a simple set of actors (as in actor model).

GPBFT is _almost_ an actor. Unfortunately, `ValidateMessage` needs to (a) be synchronous and (b) callable concurrently. We _could_ send a message on a channel to some reactor loop, then wait for a reply... but that's adding a bunch of complexity and overhead for little gain.

In general (speaking from experience, pain, and misery), don't attempt to go full-actor-model in Go. It _looks_ like it should be perfect for the language, but it really isn't: channels are not the same as an event bus (blocking with fixed capacity), it's too easy to share memory, you're missing all the sugar that makes coding in actor languages bearable, and mixing actor-like code and non-actor-like code never ends will.

For some context:

- Libp2p was originally written with channels all the way down. It was rewritten because performance sucked.
- Bitswap has gone through many "actor model" phases and is currently an absolute mess.
- Gossipsub is probably the most actor-model-like library we have, and it's still a mess.

**Comment by masih** [comment]
> an atomic plus an error... I don't feel strongly about this.

Indeed 👍 Nor do I.

Interesting, thank you for pointing out the prior work. I would instinctively think that actor model would be a good fit. "Full-actor-model" is subjective 🤷 What I had in mind was certainly more than one actor to handle things like validation. I also think that it is too early to do major refactoring; not until we get it all "correct" at least once.

**Comment by Stebalien** [comment]
> Interesting, thank you for pointing out the prior work. I would instinctively think that actor model would be a good fit.

So did we. But performance, the fact that the queues are bounded, and the fact that there's no built-in (efficient) request/response idioms make it difficult.

**Comment by anorth** [comment]
We all discussed this and resolved to use a tryLock with a panic if concurrent access is detected.
