### ISSUE TITLE
Running gpbft without active participation (passive observation)

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/go-f3#319]
It should be possible to run gpbft without being able to vote in the network.
The requirement that we receive messages from ourselves makes this impossible.
It also causes gpbft to have to be terminated if the async signing fails.

I don't have a good solution for this on top of my head.

**Comment by anorth** [comment]
The requirement to receive own messages is gone now. It's reasonably likely this will now "just work" with a host that simply ignores attempts to broadcast messages (because there's no ID or power associated with the participant).

**Comment by anorth** [comment]
One thing this might need is a flag or something to accept all chains during the QUALITY phase. A passive node has no preferred chain of their own or incentive to have one, because they're not even necessarily running or observing EC. I _think_ if we just input base chain every time, the node might be unnecessarily reluctant to accept proposals through the prepare and commit phases. But I could be wrong.

**Comment by Kubuxu** [comment]
Completely standalone operation is tracked in #13 
I think we resolved all issues with passive participation. Closing this.
