### ISSUE TITLE
Add EC VRF ticket to Tipset for weight tie-break

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-f3#7]
EC defines a tie-breaker between tipsets with equal weight in terms of the minimum VRF ticket of the blocks in the tipset. Add the required information to Tipset and update the comparison function to break ties.

**Comment by anorth** [comment]
Maybe we don't need to. Could it be ok to use a different tie-breaker than EC? It's a pain to carry this extra weight in every message just for this rare case. cc @Kubuxu

**Comment by matejpavlovic** [comment]
> The chain weight is used to select when two different values both gain a strong quorum (due to equivocating adversary).

I don't really understand this. No two different values can ever get both a strong quorum, even if all the faulty participants equivocate. This is arguably the most important property of a strong quorum.

> Maybe we don't need to. Could it be ok to use a different tie-breaker than EC?

Personally I don't see a reason why not. In the latest version of the algorithm, it even seems to me that we shouldn't even need to have to make this distinction in GossiPBFT, since the `ECCompatibleChains` at each participant will always form a linear chain, since they just correspond to the path between `baseChain` and the participant's local head. But maybe there is something outside of GossiPBFT and still part of F3 that needs to potentially use tie-brakers, even though I can't immediately think of such a situation. Is that the case?

**Comment by anorth** [comment]
We determined that a node should halt its participation in the protocol if it observes two conflicting strong quora. So there will be no ties to break.
